config/routes.rb
Rails.application.routes.draw do
  get 'welding/index'
  get 'welding/about'
  get 'welding/contact'
  get 'welding/products'
  get 'welding/services'
  root 'welding#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welding_controller.rb
class WeldingController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def products
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welding_helper.rb
module WeldingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeldingWorkshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'application'%>
    <%#= javascript_include_tag "jquery.min" %>
    <%#= javascript_include_tag "jquery.flexslider" %>
    <%#= javascript_include_tag 'application'%>

    <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  </head>

  <body>
    <%= render 'welding/partials/header'%>
    <%= yield %>
    <%= render 'welding/partials/footer'%>
  </body>
</html>

app/views/welding/_header.html.erb
		<div class="header">
		<div class="wrap">
					<div class="logo">
			<a href="<%=welding_index_path%>"><img src="/assets/logo.png" alt=""/></a>
			</div>
		<ul class="menu">
				 <li class="active"><a href="<%=welding_index_path%>">HOME</a> </li>
					 <li class="arrow"><a href="<%= welding_about_path %>">ABOUT</a> </li>
					 <li><a href="<%= welding_services_path_path%>">SERVICES</a>  </li>
					 <li><a href="<%=welding_products_path%>">PRODUCTS</a> </li>
					  <li><a href="<%=welding_contact_path%>">CONTACT</a> </li>
					    <div id="lavalamp"> </div>
					  <div class="clear"> </div>
				</ul>
				   <div class="clear"> </div>
		</div>
		<div class="clear"> </div>
		</div

app/views/welding/about.html.erb

<body>
		      <div class="wrap">
<div class="main1">	
<div class="content">
	<div class="about-grids">
			<h3>About our Company</h3>
      		<div class="about-grid">
      			<div class="about-grid1">
      				<a href="#"></a><img src="/assets/slider2.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="about-grid2">
      				
      			<ul>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt.dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				<li><a href="#">read more</a></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="clear"></div>
</div>
	

<div class="clear"></div>
</div>
<div class="sidebar">
	<div class="sidebar-grids">
			<h3>Latest News</h3>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top1.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top2.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top3.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top3.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		  <div class="clear"> </div>
      		
</div>
 <div class="clear"> </div>
</div>	
 <div class="clear"> </div>
 <div class="content-grids">
      		<div class="content-grid first-grid">
      			<ul>
      		
      				<li><h4>readable</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      			
      			</ul>
      		</div>
      		<div class="content-grid">
      			<ul>
      				
      				<li><h4>incididunt</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				
      			</ul>
      		</div>
      		<div class="content-grid last-grid">
      			<ul>
      				
      				<li><h4>eiusmod</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				
      			</ul>
      		</div>
      <div class="clear"></div>
      </div>
</div>
 </div>

</body>

app/views/welding/contact.html.erb

<body>
	
		

<div class="wrap">
			<div class="cont-main">
			<div class="section group">	
				<div class="contact_info">
				<h3>Our Location</h3>
			    	 		<div class="map">
					   			<iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265&amp;output=embed"></iframe><br><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color:#81532E;;text-align:left;font-size:12px">View Larger Map</a></small>
					   		</div>	
					   		</div>		
				<div class="col span_1_of_2">
					
			    	 	
      				
      			<div class="company_address">
				     	<h3>Company Information :</h3>
						<p>500 Lorem Ipsum Dolor Sit,</p>
						<p>22-56-2-9 Sit Amet, Lorem,</p>
						<p>USA</p>
				   		<p>Phone:(00) 222 666 444</p>
				   		<p>Fax: (000) 000 00 00 0</p>
				 	 	<p>Email: <a href="mailto:info@gmail.com">info[at]mycompany.com</a></p>
				   		<p>Follow on: <a href="#">Facebook</a>, <a href="#">Twitter</a></p>

				   </div>
				</div>				
				<div class="col span_2_of_4">
				  <div class="contact-form">
				  	<h3>Contact Form</h3>
					       <contact-form method="post" action="contact-post.html">
					    	<div>
						    	<span><input type="text" class="textbox" value="Name:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}"></span>
						    </div>
						    <div>
						    	<span><input type="text" class="textbox" value="Email:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}"></span>
						    </div>
						    <div>
						    	<span><input name="userPhone" type="text" class="textbox" value="mobile:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'mobile';}"></span>
						    </div>
						    <div>
						    	<span><textarea value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message</textarea></span>
						    </div>
						   <div>
						   		<span><input type="submit" value="Submit"></span>
						  </div>
					    </contact-form>

				    </div>
  				</div>				
		  </div>
		   <div class="clear"></div>
			</div>
</div>

</body>

app/views/welding/index.html.erb

<body>

			<!--start-image-slider---->
					<div class="image-slider">
						<!-- Slideshow 1 -->
					    <ul class="rslides" id="slider1">
					      <li><img src="/assets/slider2.jpg" alt=""></li>
					      <li><img src="/assets/slider3.jpg" alt=""></li>
					      <li><img src="/assets/slider1.jpg" alt=""></li>
					    </ul>
						 <!-- Slideshow 2 -->
					<div class="clear"> </div>
					<!--End-image-slider---->
		</div>
		<div class="main">	
			<div class="wrap">
	
<div class="content">
	<div class="content-grids">
      		<div class="content-grid first-grid">
      			<ul>
      		
      				<li><h4><img src="/assets/a.png" title="pic1" alt="">readable</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      			
      			</ul>
      		</div>
      		<div class="content-grid">
      			<ul>
      				
      				<li><h4><img src="/assets/b.png" title="pic1" alt="">incididunt</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				
      			</ul>	
      		</div>
      		<div class="content-grid last-grid">
      			<ul>
      				
      				<li><h4><img src="/assets/c.png" title="pic1" alt="">eiusmod</h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				
      			</ul>
      		</div>
      <div class="clear"></div>
      </div>
<div class="content-bottom-grids">
			<h3>About our Company</h3>
      		<div class="content-bottom-grid">
      			<div class="content-bottom-grid1">
      				<a href="#"></a><img src="/assets/cont1.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="content-bottom-grid2">
      				
      			<ul>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua consectetur adipisicing elit Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p></li>
      				<li><a href="about.html">read more</a></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<div class="sidebar">
	<div class="sidebar-grids">
			<h3>Latest News</h3>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top1.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top2.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top3.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		<div class="sidebar-grid">
      			<div class="sidebar-grid3">
      				<a href="#"><img src="/assets/top3.jpg" title="pic1" alt=""></a>
      			</div>
      			<div class="sidebar-grid4">
      				
      			<ul>
      				<li><h4><a href="#">this is a sample post1</a></h4></li>
      				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p></li>
      			</ul>
      			</div>
      			  <div class="clear"> </div>
      		</div>
      		  <div class="clear"> </div>
      		
</div>
 <div class="clear"> </div>
</div>	
 <div class="clear"> </div>
<div class="tsc_carousel_hor products-list">
	<h1>our products</h1>
          <div class="l-carousel">
            <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;"><div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;"><ul class="carousel jcarousel-list jcarousel-list-horizontal" style="overflow: hidden; position: relative; top: 0px; left: 0px; margin: 0px; padding: 0px; width: 2072px;">
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal" jcarouselindex="1" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont1.jpg" width="175" height="115" border="0"></a>
               
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-2 jcarousel-item-2-horizontal" jcarouselindex="2" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont2.jpg" width="175" height="115" border="0"></a>
                
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-3 jcarousel-item-3-horizontal" jcarouselindex="3" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont3.jpg" width="175" height="115" border="0"></a>
               
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-4 jcarousel-item-4-horizontal" jcarouselindex="4" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont4.jpg" width="175" height="115" border="0"></a>
              
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-5 jcarousel-item-5-horizontal" jcarouselindex="5" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont1.jpg" width="175" height="115" border="0"></a>
              
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-6 jcarousel-item-6-horizontal" jcarouselindex="6" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont2.jpg" width="175" height="115" border="0"></a>
                
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-7 jcarousel-item-7-horizontal" jcarouselindex="7" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont3.jpg" width="175" height="115" border="0"></a>
               
              </li>
              <li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-8 jcarousel-item-8-horizontal" jcarouselindex="8" style="float: left; list-style: none;"> <a href="#"><img src="/assets/cont4.jpg" width="175" height="115" border="0"></a>
               
              </li>
            </ul></div><div class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal" style="display: block;" disabled="disabled"></div><div class="jcarousel-next jcarousel-next-horizontal" style="display: block;"></div></div>
          </div>
          <div class="clear"> </div>
			
		<!-- DC Horizontal Carousel:Light End -->
		</div>	
 
</div>
</div>

</body>

app/views/welding/partials/_footer.html.erb
<div class="footer-bg">
<div class="wrap">
	<div class="footer-grid">
		<h3>About Us</h3>
		<ul>
			<li><a href="#">Online Shopping</a></li>
			<li><a href="#">Finance Service</a></li>
			<li><a href="#">Marketing</a></li>
			<li><a href="#">Economic News</a></li>
			<li><a href="#">Business Help</a></li>
		</ul>
	</div>
	<div class="footer-grid">
		<h3>Pages</h3>
		<ul>
			<li><a href="#">Home</a></li>
			<li><a href="#">About Us</a></li>
			<li><a href="#">Our Services</a></li>
			<li><a href="#">Contact Our Team</a></li>
			<li><a href="#">Short Code</a></li>
		</ul>
	</div>
	<div class="f-box">
		<h3>Recent Post</h3>
		<ul>
		<li class="active1"><a href="#">Join Our Facebook Page</a></li>
		<li><a href="#">Join Our Twitter</a></li>
		<li><a href="#">Rss Feed</a></li>
		<li><a href="#">Follow Us Google+</a></li>
		</ul>
	</div>
	<div class="footer-grid1">
		<h3>News-Letters</h3>
		<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. Pellentesque nulla ipsum, pretium ac ultrices non, tincidunt id quam. Mauris dignissim dolor quis risus molestie et ,</p>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<div class="clear"> </div>
<div class="copy-right">
	<p> &copy; 2013 steel. All Rights Reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
</div>
<div class="clear"></div>

app/views/welding/partials/_header.html.erb
		<div class="header">
		<div class="wrap">
					<div class="logo">
			<a href="<%=welding_index_path%>"><img src="/assets/logo.png" alt=""/></a>
			</div>
		<ul class="menu">
				 <li class="active"><a href="index.html">HOME</a> </li>
					 <li class="arrow"><a href="<%= welding_about_path %>">ABOUT</a> </li>
					 <li><a href="services.html">SERVICES</a>  </li>
					 <li><a href="products.html">PRODUCTS</a> </li>
					  <li><a href="contact.html">CONTACT</a> </li>
					    <div id="lavalamp"> </div>
					  <div class="clear"> </div>
				</ul>
				   <div class="clear"> </div>
		</div>
		<div class="clear"> </div>
		</div>

app/views/welding/products.html.erb

<body>

<div class="wrap">
			<div class="main1">
<div class="product-main">
	<h4>Our&nbsp;<a href="service.html">Products</a></h4>
	<div class="ser-para">
	
	</div>
	<div class="product-grid-list">
	<h5>Product 01</h5>
	<img src="/assets/pic1.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 02</h5>
		<img src="/assets/pic2.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et,placerat ut scelerisque Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 03</h5>
		<img src="/assets/pic3.jpg" alt="">
<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
		<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list last-grid">
	<h5>Product 04</h5>
		<img src="/assets/pic1.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 05</h5>
		<img src="/assets/pic2.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et,placerat ut scelerisque Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 06</h5>
		<img src="/assets/pic3.jpg" alt="">
<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
		<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 07</h5>
		<img src="/assets/pic2.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et,placerat ut scelerisque Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list last-grid">
	<h5>Product 08</h5>
		<img src="/assets/pic3.jpg" alt="">
<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
		<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list">
	<h5>Product 09</h5>
		<img src="/assets/pic3.jpg" alt="">
<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
		<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="product-grid-list last-grid">
	<h5>Product 10</h5>
		<img src="/assets/pic1.jpg" alt="">
	<p>Qsi turpis, pellentesque at ultrices in, dapibus in magna. Nunc easi diam risus, placerat ut scelerisque et, placerat ut scelerisque ,Nunc easi diam risus, placerat ut scelerisque et, </p>
	<div class="readmore">
			<p><a href="#">Read More</a></p>
		</div>
	</div>
	<div class="clear"></div>
	</div>
	
	<div class="clear"></div>
</div>

</div>

</body>